ice-lab/icepkg

package.json
packages/build-plugin-component/package.json
packages/build-plugin-component/src/index.js
packages/build-plugin-component/src/utils/modifyPkgHomePage.js

Close https://github.com/alibaba/ice/issues/3347

fix component unpkgHost

---

packages/iceworks-cli/package.json
packages/iceworks-cli/src/command/generate/generateMaterialData.ts
packages/iceworks-cli/src/command/init/addSingleMaterial.ts
packages/iceworks-cli/src/command/init/ejsRenderDir.ts
packages/iceworks-cli/src/command/init/initMaterialAndComponent.ts

- Close https://github.com/alibaba/ice/issues/3332 Close https://github.com/ice-lab/iceworks-cli/issues/2
- 截图兼容 jpg Close https://github.com/alibaba/ice/issues/3285
- Close https://github.com/ice-lab/iceworks-cli/issues/7
- Close https://github.com/ice-lab/iceworks-cli/issues/4

iceworks CLI 3.2.6

---

packages/generate-project/CHANGELOG.md
packages/generate-project/package.json
packages/generate-project/src/fommatProject.ts

feat: support govfe custom generate

---

examples/rax-component/demo/basic.md
packages/build-plugin-component/package.json
packages/build-plugin-component/src/compiler/babel.js
packages/build-plugin-component/src/configs/rax/web/dev.js
packages/build-plugin-component/src/configs/rax/weex/dev.js
packages/build-plugin-component/src/rax.js
packages/build-plugin-component/src/template/raxEntry.hbs
packages/build-plugin-component/src/template/raxTemplate.hbs
packages/build-plugin-component/src/utils/generateEntry.js
packages/template-component-demo/package.json
packages/template-component-demo/src/Playground/CodeBox.jsx

> rax 组件开发的 demo 会以 entry 方式独立生成 bundle，即新增一个 demo 就需要增加一个 entry，这就需要重启 webpack，目前仅实现了监听变更

fix: rax demo style

---

.github/workflows/ci.yml
packages/build-plugin-component/package.json
packages/build-plugin-component/src/compiler/babel.js
packages/build-plugin-component/src/configs/rax/getBaseWebpack.js
packages/build-plugin-component/src/configs/rax/getDemoConfig.js
packages/build-plugin-component/src/configs/rax/miniapp/getBase.js
packages/build-plugin-component/src/configs/rax/userConfig.js
packages/build-plugin-component/src/configs/userConfig.js
packages/build-plugin-component/src/constants.js
packages/build-plugin-component/src/rax.js
packages/build-plugin-component/src/utils/raxDevCompileLog.js

build-plugin-component@1.1.0

---

packages/build-plugin-component/src/template/raxPortal.html

fix https://github.com/ice-lab/iceworks-cli/issues/61

fix: Portal preview window set flex-basis

---

examples/react-component/build.json
packages/build-plugin-component/package.json
packages/build-plugin-component/src/configs/react/userConfig.js
packages/build-plugin-component/src/react.js

hotfix: htmlInjection compatible with mulit webpack config

---

packages/build-plugin-component/package.json
packages/build-plugin-component/src/configs/rax/getDemoConfig.js
packages/build-plugin-component/src/configs/rax/getDistConfig.js
packages/build-plugin-component/src/rax.js
packages/build-plugin-component/src/template/raxDemo.html

1.  css failure when syning to fusion material
✅ Closes: #86

fix: 🐛 css failure when syning to fusion material

---

.gitignore
packages/build-plugin-component/package.json
packages/build-plugin-component/src/compiler/babel.js
packages/build-plugin-component/src/configs/rax/getDemoConfig.js
packages/build-plugin-component/src/configs/rax/miniapp/getBase.js
packages/build-plugin-component/src/rax.js
packages/build-plugin-component/src/template/device.hbs
packages/build-plugin-component/src/template/miniapp/ali-miniapp/mini.project.json
packages/build-plugin-component/src/template/raxEntry.hbs
packages/build-plugin-component/src/template/raxPortal.html
packages/build-plugin-component/src/utils/generateEntry.js
packages/build-plugin-component/src/utils/generateRaxDemo.js
packages/build-plugin-component/src/utils/getDemos.js
packages/build-plugin-component/src/utils/getPortalModules.js
packages/build-plugin-component/src/utils/getReadme.js
packages/build-plugin-component/src/utils/handlePaths.js

feat: 🎸 alternation for build-plugin-miniapp-preview

---

.gitignore
packages/build-plugin-component/package.json
packages/build-plugin-component/src/compiler/babel.js
packages/build-plugin-component/src/configs/rax/getDemoConfig.js
packages/build-plugin-component/src/configs/rax/getDistConfig.js
packages/build-plugin-component/src/configs/rax/miniapp/getBase.js
packages/build-plugin-component/src/rax.js
packages/build-plugin-component/src/template/device.hbs
packages/build-plugin-component/src/template/miniapp/ali-miniapp/mini.project.json
packages/build-plugin-component/src/template/raxDemo.html
packages/build-plugin-component/src/template/raxEntry.hbs
packages/build-plugin-component/src/template/raxPortal.html
packages/build-plugin-component/src/utils/generateEntry.js
packages/build-plugin-component/src/utils/generateRaxDemo.js
packages/build-plugin-component/src/utils/getDemos.js
packages/build-plugin-component/src/utils/getPortalModules.js
packages/build-plugin-component/src/utils/getReadme.js
packages/build-plugin-component/src/utils/handlePaths.js

<del> - [ ] supoort codepen #22 </del>

Release: build-plugin-component 1.3.0

---

examples/rax-component-skip-demos/.editorconfig
examples/rax-component-skip-demos/.gitignore
examples/rax-component-skip-demos/README.md
examples/rax-component-skip-demos/build.json
examples/rax-component-skip-demos/package.json
examples/rax-component-skip-demos/src/index.less
examples/rax-component-skip-demos/src/index.tsx
examples/rax-component-skip-demos/tsconfig.json
packages/build-plugin-component/package.json
packages/build-plugin-component/src/rax.js

hotfix: build fail when skipping demos

---

packages/build-plugin-component/package.json
packages/build-plugin-component/src/rax.js

fix: build fail when skipping demos

---

packages/build-plugin-component/package.json
packages/build-plugin-component/src/template/raxEntry.hbs
packages/build-plugin-component/src/template/raxPortal.html
packages/build-plugin-component/src/utils/generateRaxDemo.js

unify layout style with herbox for build-plugin-component

feat: new layout for miniapp preview

---

packages/generate-project/package.json
packages/generate-project/src/fommatProject.ts

chore: update def plugin version

---

packages/build-plugin-component/src/react.js

feat: 🎸 react support watchDist

---

packages/build-plugin-component/package.json
packages/build-plugin-component/src/utils/markdownHelper.js

feat: 🎸 update js yaml to v4

---

packages/build-plugin-component/src/compiler/babel.js

feat: 🎸 support cross terminal

---

packages/build-plugin-component/package.json
packages/build-plugin-component/src/configs/rax/getDistConfig.js
packages/build-plugin-component/src/configs/rax/getRuntimeMiniappConfig.js
packages/build-plugin-component/src/constants.js
packages/build-plugin-component/src/rax.js
packages/build-plugin-component/src/template/miniapp/ali-miniapp-runtime/app.acss
packages/build-plugin-component/src/template/miniapp/ali-miniapp-runtime/app.js
packages/build-plugin-component/src/template/miniapp/ali-miniapp-runtime/config.js
packages/build-plugin-component/src/template/miniapp/ali-miniapp-runtime/default.acss
packages/build-plugin-component/src/template/miniapp/ali-miniapp-runtime/pages/Demo/index.acss
packages/build-plugin-component/src/template/miniapp/ali-miniapp-runtime/pages/Demo/index.axml
packages/build-plugin-component/src/template/miniapp/ali-miniapp-runtime/pages/Demo/index.js
packages/build-plugin-component/src/template/miniapp/ali-miniapp-runtime/pages/Demo/index.json
packages/build-plugin-component/src/template/miniapp/ali-miniapp-runtime/render.js
packages/build-plugin-component/src/template/miniapp/ali-miniapp-runtime/root.axml
packages/build-plugin-component/src/template/miniapp/ali-miniapp-runtime/tool.sjs
packages/build-plugin-component/src/template/raxEntry.hbs
packages/build-plugin-component/src/template/raxPortal.html
packages/build-plugin-component/src/template/runtimeMiniappDemoEntry.hbs
packages/build-plugin-component/src/template/runtimeMiniappPage.hbs
packages/build-plugin-component/src/utils/copyRuntimeMiniappFiles.js
packages/build-plugin-component/src/utils/generateRaxDemo.js
packages/build-plugin-component/src/utils/generateRuntimeAppJson.js
packages/build-plugin-component/src/utils/generateRuntimeDemoEntry.js
packages/build-plugin-component/src/utils/generateRuntimeMiniappPages.js
packages/build-plugin-component/src/utils/getDemos.js
packages/build-plugin-component/src/utils/setCSSRule.js
packages/build-plugin-component/src/webpackPlugins/runtimeFunctionWrapperPlugin.js

1. building runtime project locally
2. building  herbox

feat: suppport building runtime miniapp component

---

packages/ice-npm-utils/CHANGELOG.md
packages/ice-npm-utils/README.md
packages/ice-npm-utils/package.json
packages/ice-npm-utils/src/__tests__/index.ts
packages/ice-npm-utils/src/index.ts

export getVersions 和 getSatisfiesVersions 方法，上层通过此方法获取所有包版本

feat add getVersions method

---

packages/build-plugin-component/CHANGELOG.md
packages/build-plugin-component/package.json
packages/build-plugin-component/src/react.js
packages/build-plugin-component/src/template/raxEntry.hbs
packages/build-plugin-component/src/template/raxPortal.html
packages/build-plugin-component/src/template/raxTemplate.hbs
packages/build-plugin-component/src/utils/generateRaxDemo.js
packages/build-plugin-component/src/utils/markdownHelper.js

[WIP] Release

---

packages/build-plugin-component/src/configs/rax/kraken/dev.js
packages/build-plugin-component/src/constants.js
packages/build-plugin-component/src/rax.js
packages/build-plugin-component/src/utils/raxDevCompileLog.js

feat: 🎸 support kraken

---

packages/build-plugin-component/package.json

feat: 🎸 update marked version

---

packages/build-plugin-component/CHANGELOG.md
packages/build-plugin-component/package.json
packages/build-plugin-component/src/configs/rax/kraken/dev.js
packages/build-plugin-component/src/constants.js
packages/build-plugin-component/src/rax.js
packages/build-plugin-component/src/utils/raxDevCompileLog.js

build-plugin-component 1.4.0

---

packages/build-plugin-component/src/utils/generateEntry.js

fix: 🐛 escape dollar

---

packages/ice-npm-utils/package.json
packages/ice-npm-utils/src/index.ts

chore: better error message

---

packages/build-plugin-component/src/compiler/depAnalyze.js
packages/build-plugin-component/src/utils/getUMDWebpack.js

feat: external next

---

packages/build-plugin-component/src/utils/getUMDWebpack.js
packages/build-plugin-component/src/utils/htmlInjection.js

fix: 🐛 fix beta error

---

packages/generate-project/CHANGELOG.md
packages/generate-project/package.json
packages/generate-project/src/formatProject.ts

默认关闭埋点方案的创建和同步，免于在初建时，出现权限相关提示，并预留手动指定 appInfoId 的时机

set goldlog = false

---

packages/build-plugin-component/CHANGELOG.md
packages/build-plugin-component/package.json
packages/build-plugin-component/src/compiler/generateStyle.js

fix: 🐛 reslove modules upward

---

packages/build-plugin-component/CHANGELOG.md
packages/build-plugin-component/src/utils/getUMDWebpack.js

fix: 🐛 external commonjs

---

packages/build-plugin-component/CHANGELOG.md
packages/build-plugin-component/package.json
packages/build-plugin-component/src/utils/getUMDWebpack.js

build-plugin-component 1.6.2

---

packages/build-plugin-component/CHANGELOG.md
packages/build-plugin-component/package.json
packages/build-plugin-component/src/utils/formatPathForWin.js
packages/build-plugin-component/src/utils/generateRaxDemo.js
packages/build-plugin-component/src/utils/getDemos.js

fix: 🐛 support win32

---

jest.config.js
package.json
packages/ice-npm-utils/src/__tests__/index.ts
packages/iceworks-cli/CHANGELOG.md
packages/iceworks-cli/package.json
packages/iceworks-cli/src/command/generate/generateMaterialData.ts
packages/iceworks-cli/src/template/initMaterial/tsconfig.json

有时候物料代码在另一个仓库里，但是想要在另一个物料源里显示，这时候通过加一个 package.json 来实现（类似一个引用）。
比如 `fusion-design-pro` 的代码都在 `alibaba-fusion/materials` 这个仓库，但是我想在 `ice-lab/react-materials` 里也显示这个模板。

feat: material latest version

---

packages/generate-project/CHANGELOG.md
packages/generate-project/package.json
packages/generate-project/src/formatScaffoldToProject.ts
packages/ice-npm-utils/src/__tests__/index.ts

* 统一使用  glob 
* 添加 ignore 目录
* 修复 ci

Feat update fs-readdir-recursive to glob

---

packages/generate-project/CHANGELOG.md
packages/generate-project/package.json
packages/generate-project/src/formatProject.ts

feat: compate def

---

packages/build-plugin-block/CHANGELOG.md
packages/build-plugin-block/package.json
packages/build-plugin-component/package.json

Feat/upgrade build scripts to 1.0.0

---

packages/build-plugin-component/CHANGELOG.md
packages/build-plugin-component/package.json
packages/build-plugin-component/src/compiler/babel.js

fix: 🐛 inlineStyle false mulit css

---

packages/build-plugin-component/src/compiler/dts.js

fix: dts file generate error at windows

---

packages/build-plugin-component/CHANGELOG.md
packages/build-plugin-component/package.json
packages/build-plugin-component/src/compiler/babel.js

fix: 🐛 修复 inlineStyle 默认为 true 这一行为逻辑的 break change

---

packages/build-plugin-component/package.json
packages/build-plugin-component/src/compiler/babel.js
packages/build-plugin-component/src/configs/react/userConfig.js
packages/build-plugin-component/src/utils/getUMDWebpack.js

[plugin-component] support define option

---

packages/build-plugin-component/src/compiler/dts.js

feat: 🎸 generate dts in win32

---

packages/build-plugin-component/src/compiler/dts.js

dts  不应该只关注ts文件
比如js+jsDoc的， 或者纯js 的

fix: use REG_JS

---

packages/build-plugin-component/CHANGELOG.md
packages/build-plugin-component/package.json
packages/build-plugin-component/src/compiler/babel.js
packages/build-plugin-component/src/configs/rax/getBaseWebpack.js
packages/build-plugin-component/src/configs/rax/userConfig.js
packages/build-plugin-component/src/configs/react/userConfig.js
packages/build-plugin-component/src/configs/userConfig.js
packages/build-plugin-component/src/useConfig/define.js
packages/build-plugin-component/src/utils/getUMDWebpack.js

fix: 🐛 provide consistency of `define` between rax & react

---

packages/build-plugin-component/CHANGELOG.md
packages/build-plugin-component/package.json
packages/build-plugin-component/src/compiler/babel.js
packages/build-plugin-component/src/compiler/dts.js
packages/build-plugin-component/src/configs/rax/getBaseWebpack.js
packages/build-plugin-component/src/configs/rax/userConfig.js
packages/build-plugin-component/src/configs/react/userConfig.js
packages/build-plugin-component/src/configs/userConfig.js
packages/build-plugin-component/src/useConfig/define.js
packages/build-plugin-component/src/utils/getUMDWebpack.js

Release: plugin-component 1.8.1

---

packages/generate-project/CHANGELOG.md
packages/generate-project/package.json
packages/generate-project/src/__tests__/index.ts
packages/generate-project/src/formatProject.ts

Fix https://github.com/alibaba/rax/issues/2311

chore: remove build.json web.pha when not ali env

---

packages/build-plugin-component/CHANGELOG.md
packages/build-plugin-component/package.json
packages/build-plugin-component/src/configs/userConfig.js

feat: 🎸 default cors middleware

---

examples/react-component/build.json
examples/react-component/package.json
examples/react-component/src/index.tsx
packages/build-plugin-component/CHANGELOG.md
packages/build-plugin-component/src/compiler/babel.js
packages/build-plugin-component/src/utils/getCompileBabel.js

use babel-plugin-import transform `import { Foo } from 'package'` consider `esm/` libraryDirectory, for `@formily/next-components`
修复后：

use babel-plugin-import transform consider `esm/` libraryDirectory(es/+esm/)

---

packages/build-plugin-component/README.md

- chore: fix how to use [t|j]s in demo dirs

Readme: fix how to use [t|j]s in demo dirs

---

packages/ice-npm-utils/CHANGELOG.md
packages/ice-npm-utils/package.json
packages/ice-npm-utils/src/__tests__/index.ts
packages/ice-npm-utils/src/index.ts

Relate to https://github.com/ice-lab/iceworks-cli/pull/287

[ice-npm-utils] fix: 🐛 semver error

---

packages/template-component-demo/package.json

keep the same version of react in peerDependencies and devDependencies

[template-component-demo] Update peerDependency

---

packages/iceworks-cli/CHANGELOG.md
packages/iceworks-cli/bin/iceworks.js
packages/iceworks-cli/package.json
packages/iceworks-cli/src/command/add/index.ts
packages/iceworks-cli/src/command/generate/index.ts
packages/iceworks-cli/src/command/init/addSingleMaterial.ts
packages/iceworks-cli/src/command/init/index.ts
packages/iceworks-cli/src/template/initMaterial/README.md

release: iceworks-cli@3.4.10

---

examples/package/build.config.ts
packages/pkg/src/helpers/load.ts
packages/pkg/src/loaders/transform.ts

closes https://github.com/ice-lab/icepkg/issues/295

fix: 🐛 fix excludes

---

packages/plugin-docusaurus/src/configureDocusaurus.mts
packages/plugin-docusaurus/src/template/docusaurus.hbs

fix: 🐛 docusaurus builds error when no static dir exist

---

packages/pkg/src/build.ts
packages/pkg/src/cli.ts
packages/pkg/src/helpers/pluginContainer.ts

fix: 🐛 be consistent of rollup's extended error

---

packages/plugin-docusaurus/src/template/docusaurus.hbs
website/docusaurus.config.js

- docs: update navbar
- feat: set defaultLocale to zh-Hans in preview

docs: update navbar && update preview locale

---

packages/create-pkg/CHANGELOG.md
packages/create-pkg/package.json
packages/create-pkg/src/inquirePackageName.ts
packages/create-pkg/src/langs/en-US.ts
packages/create-pkg/src/langs/zh-CN.ts

- [fix] can't check ali Intranet correctly
- [feat] remove prompt of scope choose if in ali Intranet

fix(create-pkg): can't check ali Intranet correctly

---

packages/plugin-docusaurus/src/plugin.js

throw error if rax-compat is not installed in react component development

fix(plugin-docusaurus): throw error if rax-compat is not installed

---

packages/pkg/src/helpers/load.ts
packages/pkg/src/plugins/dts.ts
packages/pkg/src/utils.ts

fix: transform d.ts and mix use ts/js

---

packages/build-plugin-component/src/compiler/babel.js
packages/build-plugin-component/src/utils/mergeBabelPlugins.js

feat: fix babelPluginsMerge

---

examples/react-component/src/typings.d.ts
examples/react-multi-components/src/typings.d.ts
packages/pkg/package.json
packages/pkg/types.d.ts

增加 pkg 内置的类型，在项目中的 `src/typings.d.ts` 中直接通过 `/// <reference types="@ice/pkg/types" />` 引入类型，获得更好的类型提示

feat: add default type

---

packages/pkg/src/helpers/suffix.ts
packages/pkg/src/rollupPlugins/dts.ts

dev 阶段，随便用户不断修改-保存代码，导致 `ids` 这个数组会被不断添加重复 id，即使文件没变更，也会不断编译生成 d.ts 文件

fix: compile all files in dev

---

packages/plugin-docusaurus/CHANGELOG.md
packages/plugin-docusaurus/package.json
packages/plugin-docusaurus/src/configureDocusaurus.mts
packages/plugin-docusaurus/src/constants.mts
packages/plugin-docusaurus/src/doc.mts
packages/plugin-docusaurus/src/index.mts
packages/plugin-docusaurus/src/types.mts
pnpm-lock.yaml

chore: update plugin docusaurus ts types

---

packages/create-pkg/package.json
packages/pkg/package.json
packages/plugin-docusaurus/package.json
packages/plugin-rax-component/package.json

丢失掉 access=public 发布到 npm 不成功
https://github.com/ice-lab/icepkg/actions/runs/4072239655/jobs/7014833276

chore: add package publish config

---

packages/plugin-docusaurus/src/template/docusaurus.hbs
packages/plugin-docusaurus/src/types.mts

支持配置 docusaurus 插件，详见：https://github.com/ice-lab/icepkg/issues/427

feat: support plugin for docusaurus (#427)

---

.changeset/sixty-poets-fetch.md
packages/pkg/src/helpers/dts.ts
packages/pkg/src/helpers/getTaskIO.ts

- dev 阶段代码热更新时候，生成 .d.ts 文件过程失败报错
- Windows 系统上生成 .d.ts 文件报错

fix: generate dts file error

---

.changeset/happy-crabs-attend.md

给 https://github.com/ice-lab/icepkg/pull/442 增加 changeset

chore: add docusaurus plugin changeset

---

.changeset/loud-meals-attack.md
examples/react-component/build.config.mts
examples/react-component/package.json
examples/react-component/src/components/Button.tsx
examples/react-component/src/index.tsx
packages/plugin-jsx-plus/CHANGELOG.md
packages/plugin-jsx-plus/README.md
packages/plugin-jsx-plus/build.config.mts
packages/plugin-jsx-plus/package.json
packages/plugin-jsx-plus/src/index.ts
pnpm-lock.yaml
website/docs/guide/jsx-plus.md
website/docusaurus.config.js

feat: jsx-plus plugin

---

.changeset/perfect-jars-learn.md
packages/pkg/package.json
packages/pkg/src/rollupPlugins/babel.ts
pnpm-lock.yaml

问题：使用 babel-plugin-import 后组件丢失
源码：
编译产物：

fix: transform code error with babel plugin

---

examples/react-component/package.json
examples/react-component/pages/index.tsx
examples/react-component/tsconfig.json
packages/plugin-docusaurus/package.json
packages/plugin-docusaurus/src/index.mts
packages/plugin-docusaurus/src/remark/extractCode.js
packages/plugin-docusaurus/src/remark/getFileInfo.js
packages/plugin-docusaurus/src/template/docusaurus.hbs
packages/plugin-docusaurus/src/types.mts
pnpm-lock.yaml
website/docs/guide/preview.md
website/package.json

Resolve: https://github.com/ice-lab/icepkg/issues/416

feat: support configure index page

---

.github/workflows/release.yml
.github/workflows/version.yml

https://github.com/ice-lab/icepkg/actions/runs/4160796829/jobs/7198109987
安装依赖的时候直接报错，怀疑跟 npm 的 register 不一样有关系

fix: run pnpm install error

---

.changeset/loud-wolves-teach.md
packages/pkg/src/rollupPlugins/minify.ts

fix: minified can not run in sarafi

---

.changeset/rich-rice-drum.md
examples/rax-component/README.md
examples/rax-component/build.config.mts
examples/rax-component/docs/index.md
examples/rax-component/docs/usage.md
examples/rax-component/docs/usage.module.css
examples/rax-component/package.json
examples/rax-component/src/index.module.css
examples/rax-component/src/index.tsx
examples/rax-component/src/typings.d.ts
examples/rax-component/tsconfig.json
packages/pkg/src/helpers/getRollupOptions.ts
packages/pkg/src/rollupPlugins/babel.ts
packages/plugin-jsx-plus/src/index.ts
pnpm-lock.yaml
website/docs/guide/jsx-plus.md

Ref: https://github.com/ice-lab/icepkg/issues/472

fix: jsx-plus can not be used in rax components

---

.changeset/yellow-eels-jog.md
packages/create-pkg/src/inquireProjectType.ts
packages/create-pkg/src/langs/en-US.ts

chore: project type list items order

---

packages/pkg/bin/cli.mjs

fix: dist cli option exists

---

website/docs/guide/preview.md

- 在预览文档（plugin-docusaurus）中新增插件选项（plugins）支持配置 docusaurus 插件
- 优化文档中的选项值

docs: add docusaurus plugin documentation

---

website/docs/faq.md
website/docs/guide/abilities.md

1. 增加使用 scss 或 less 时需要安装依赖的说明
2. 出现 scss-loader/less-loader 找不到的报错时的解决方案

docs: style dependency

---

website/docs/guide/monorepo.md
website/docusaurus.config.js

docs: monorepo

---

.changeset/friendly-balloons-perform.md
packages/create-pkg/package.json
packages/pkg/README.md
packages/pkg/package.json
packages/plugin-docusaurus/README.md
packages/plugin-docusaurus/build.config.mts
packages/plugin-docusaurus/package.json
packages/plugin-jsx-plus/package.json
packages/plugin-rax-component/README.md
packages/plugin-rax-component/package.json
pnpm-lock.yaml
website/docs/guide/preview.md

- 更新每个 npm 包中 package.json 里信息，比如 bugs, repository, engines 等
- 补充包的 README 信息

chore: add fields to package.json and update README

---

.changeset/wise-spiders-film.md

https://github.com/ice-lab/icepkg/pull/515 漏了 plugin-docusaurus 的 changelog

chore: add plugin-docusaurus changelog

---

.changeset/fast-seahorses-lick.md
packages/plugin-docusaurus/src/Previewer/styles.css

fix: mobile preview style

---

.changeset/silly-ears-pump.md
packages/create-pkg/src/index.mts

fix: npmName is empty when create template

---

packages/plugin-docusaurus/package.json
packages/remark-react-docgen-docusaurus/package.json
pnpm-lock.yaml

升级 plugin-docusaurus 和 remark-react-docgen-docusaurus 的 `@swc/helpers` 到 0.5.1 版本

chore: upgrade @swc/helpers version

---

.changeset/lovely-zoos-sip.md

新增 `@ice/remark-react-docgen-docusaurus`  `@ice/pkg-plugin-docusaurus` changelog

chore: add changelog and version

---

.changeset/config.json
package.json

ref: https://github.com/alibaba/ice/issues/6174

feat: add release snapshot script

---

.changeset/thick-wombats-look.md
packages/pkg/CHANGELOG.md
packages/pkg/package.json
packages/pkg/src/config/userConfig.ts
packages/pkg/src/helpers/getRollupOptions.ts
packages/pkg/src/rollupPlugins/babel.ts
packages/pkg/src/rollupPlugins/swc.ts
packages/pkg/src/types.ts
packages/pkg/src/utils.ts
website/docs/reference/config.md

Release @ice/pkg@1.5.8

---

.changeset/heavy-dodos-joke.md
packages/plugin-docusaurus/src/configureDocusaurus.mts
packages/plugin-docusaurus/src/remark/extractCode.js
packages/plugin-docusaurus/src/remark/getFileInfo.js
packages/plugin-docusaurus/src/remark/resolveImports.js

 fix: Doc build failed in windows

---

.changeset/six-pianos-burn.md
packages/pkg/src/helpers/getRollupOptions.ts

多 entry 的模式下，支持生成 vendor chunk（包含公共模块和 node_modules）

feat: generate vendor chunk

---

.changeset/long-jokes-thank.md
packages/plugin-docusaurus/src/genDemoPages/extractCodePlugin.mts
packages/plugin-docusaurus/src/genDemoPages/index.mts
packages/plugin-docusaurus/src/remark/extractCode.js
packages/plugin-docusaurus/src/remark/fixedFilename.js
packages/plugin-docusaurus/src/remark/getFileInfo.js
pnpm-lock.yaml

feat: remove hash string from demo path for debugging easier

---

.changeset/violet-rocks-tickle.md
packages/pkg/src/helpers/getBabelOptions.ts
packages/pkg/src/helpers/getRollupOptions.ts
packages/pkg/src/rollupPlugins/babel.ts
packages/pkg/src/types.ts

feat: 添加modifyBabelOptions

---

.changeset/twelve-glasses-sniff.md
packages/pkg/src/helpers/getBabelOptions.ts
packages/pkg/src/helpers/getRollupOptions.ts
packages/pkg/src/rollupPlugins/babel.ts
packages/pkg/tests/babelPlugin.test.ts

feat(babel-plugin): support jsxruntime

---

.github/workflows/release-snapshot.yml

手动触发 workflow 发布 snapshot 版本
https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow

feat: add release snapshot github action

---

packages/plugin-docusaurus/CHANGELOG.md
packages/plugin-docusaurus/package.json
packages/plugin-docusaurus/src/configureDocusaurus.mts
packages/plugin-docusaurus/src/template/docusaurus.hbs
packages/plugin-docusaurus/src/types.mts

support navbar items configuration

support navbar items configuration

---

packages/plugin-docusaurus/CHANGELOG.md
packages/plugin-docusaurus/package.json
packages/plugin-docusaurus/src/remark/extractCode.js
packages/plugin-docusaurus/src/template/docusaurus.hbs
packages/plugin-docusaurus/src/types.mts

feat: add mobilePreviewUrlParams

---

.changeset/fluffy-penguins-buy.md
packages/pkg/src/config/userConfig.ts
packages/pkg/src/helpers/getRollupOptions.ts
packages/pkg/src/types.ts

feat: add declaration

---

packages/pkg/src/utils.ts
packages/pkg/tests/createScriptsFilter.test.ts

Some dependencies can not compiled because of the wrong regular expression.

fix: not compile some deps

---

packages/pkg/CHANGELOG.md
packages/pkg/package.json
pnpm-lock.yaml

chore: upgrade @swc/core version
