ice-lab/icepkg

packages/build-plugin-component/CHANGELOG.md
packages/build-plugin-component/package.json
packages/build-plugin-component/src/utils/modifyPkgHomePage.js

path.join 的拼接会让 // 转化 /，导致 homepage 链接错误

fix: invalid link of homepage

---

packages/build-plugin-component/CHANGELOG.md
packages/build-plugin-component/package.json
packages/build-plugin-component/src/utils/setCSSRule.js

fix: 🐛 compatible with mini-css-extract-plugin 1.x

---

packages/build-plugin-component/CHANGELOG.md
packages/build-plugin-component/package.json

feat(miniapp): update compile miniapp version

---

packages/build-plugin-component/src/compiler/depAnalyze.js

修复再对es目录进行依赖分析时，React.lazy里面进行import的模块没有被分析出来
```js
var PlatformMap = {
mobile: /*#__PURE__*/React.lazy(function () {
return import('./mobile');
})
};
```

feat: fix React.lazy import analyze fail

---

examples/react-component/build.json
examples/react-component/package.json
examples/react-component/src/index.tsx
packages/build-plugin-component/CHANGELOG.md
packages/build-plugin-component/package.json
packages/build-plugin-component/src/compiler/babel.js
packages/build-plugin-component/src/compiler/depAnalyze.js
packages/build-plugin-component/src/utils/getCompileBabel.js

[plugin-component] release build-plugin-component/1.9.4

---

packages/build-plugin-component-screenshot/CHANGELOG.md
packages/build-plugin-component-screenshot/README.md
packages/build-plugin-component-screenshot/package.json
packages/build-plugin-component-screenshot/src/index.js
packages/build-plugin-component-screenshot/src/screenshot/index.js

我们想在组件展示平台展示组件的截图，但是构建之后的截图文件名无法被组件展示平台获取。因此需要一个固定路径的 JSON 文件存储所有截图文件的相对路径。此 PR 会生成 `build/screenshots.json` 文件，内容为：
```json
[
"views/basic.png",
"views/disable-row-actions.png",
"views/fixed-height.png",
"views/hide-checkboxes.png",
"views/hide-footer.png",
"views/small.png"
]
```
另外，目前 DEF 云构建已经支持 puppeteer 了，因此不再需要 cloud 选项。同时需要增加选项 `{ args: ['--no-sandbox'] }` 才能云构建。

[plugin-component-screenshot] feat: write screenshots.json

---

packages/ice-npm-utils/src/index.ts

According to the description of sort on [mdn](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#description), the compareFunction should return a number.
The current implementation is not working properly, see the following simple test which can be copy and executed in the browser console.
```js
[  '0.2.4', '0.2.5' ].sort((a, b) => {
return b > a;
});
// console ['0.2.4', '0.2.5']
```
```js
[  '0.2.4', '0.2.5' ].sort((a, b) => {
return b > a ? 1 : -1;
});
// console ['0.2.5', '0.2.4']
```

fix(ice-npm-utils): fix sort problem in getLatestSemverVersion

---

packages/ice-npm-utils/CHANGELOG.md
packages/ice-npm-utils/package.json
packages/ice-npm-utils/src/__tests__/index.ts
packages/ice-npm-utils/src/index.ts
packages/iceworks-cli/CHANGELOG.md
packages/iceworks-cli/bin/iceworks.js
packages/iceworks-cli/package.json
scripts/publish.ts

- iceworks-cli 发布新版本，提示用户迁移到 `@appworks/cli`
- ice-npm-utils@2.x 修改 cnpm 默认的 registry，因为这个版本目前下载量还挺高的（最新的 3.x 版本已修改）

feat(iceworks-cli): add migrate appworks cli message

---

examples/package/build.config.ts
packages/pkg/src/loaders/transform.ts
packages/pkg/src/plugins/dts.ts

fix: 🐛 resolve load hooks params

---

examples/package/src/index.tsx
packages/pkg/src/helpers/dts.ts
packages/pkg/src/plugins/dts.ts
packages/pkg/src/utils.ts

@ice/pkg generates declarations two times faster after setting `skipLibCheck`.
```shell
[DTS] Generating declaration files take 5264.9ms
```
```shell
[DTS] Generating declaration files take 2116.65ms
```
But there exists a question: should `defaultTypescriptOptions` be overridden by tsconfig configurations.

chore: 🤖 speed up generating declaration

---

packages/pkg/src/helpers/normalizeRollupConfig.ts

fix: 🐛 erorr when externals

---

packages/pkg/src/loaders/transform.ts
packages/plugin-docusaurus/src/doc.mts

产物代码中如果存在 @swc/helpers 但是用户未安装，则会在控制台给出 warning 提示。该提示较弱用户可能忽略，现调整为以下策略：
- 控制台提示由 warning 升级为 error
- 直接终止编译和预览任务。用户需手动安装 @swc/helpers 之后才可继续开发

feat: exit process if @swc/helpers is not installed

---

packages/plugin-docusaurus/CHANGELOG.md
packages/plugin-docusaurus/package.json
packages/plugin-docusaurus/src/configureDocusaurus.mts
packages/plugin-docusaurus/src/plugin.js

<></> 默认编译为 React.Fragment，而 React 在 automatic 模式下不再必须引入，因此在预览构建时可能出现 React is not defined 的报错。
现直接将其编译为 Fragment，并通过 webpack provider plugin 直接全局注入

fix(plugin-docusaurus): can't use short syntax (<></>) of fragment

---

packages/pkg/bin/cli.mjs
packages/pkg/src/build.ts
packages/pkg/src/buildAll.ts
packages/pkg/src/config/userConfig.ts
packages/pkg/src/defineConfig.ts
packages/pkg/src/helpers/__tests__/getTaskIO.test.ts
packages/pkg/src/helpers/getTaskIO.ts
packages/pkg/src/helpers/logger.ts
packages/pkg/src/helpers/mergeConfigOptions.ts
packages/pkg/src/helpers/normalizeRollupConfig.ts
packages/pkg/src/helpers/reportSize.ts
packages/pkg/src/loaders/bundle.ts
packages/pkg/src/loaders/transform.ts
packages/pkg/src/plugins/component.ts
packages/pkg/src/types.ts
packages/pkg/src/utils.ts

1. support multi entry support for bundle mode
2. pretty console output and add dir info

feat: support multi entry

---

packages/pkg/package.json
packages/pkg/src/helpers/defaultSwcConfig.ts
packages/pkg/src/helpers/dts.ts
packages/pkg/src/helpers/formatAliasToTSPathsConfig.ts
packages/pkg/src/helpers/getRollupOptions.ts
packages/pkg/src/rollupPlugins/dts.ts
pnpm-lock.yaml

原始文件：
构建出来的 d.ts 文件内容差异
原因是，tsx 代码先经过 swc 编译，这时候类型被擦除掉了，最后再交给 dts 插件处理的时候，就没有类型了。
1.4.0 的改动是为了修复 alias 在 d.ts 中没有被转成相对路径的问题。其实这里 swc、dts、alias 插件之前是会有循环相互依赖的问题 = = 
dts 插件里面内置一个 ts 插件 @zerollup/ts-transform-paths，这个插件在声明文件之后把 d.ts 的  alias 转成相对路径
理论上，dts 插件和 swc 插件两个不相关了，可以并行执行的

fix: some export types was remove in d.ts

---

.changeset/README.md
.github/workflows/version.yml
package.json

- 在 ci 上执行 version 修改时，需要同时更新掉 lock 的内容，否则 lock 不同步
- 新增发包流程说明

chore: update changeset version script and readme

---

.changeset/big-donkeys-sit.md
packages/pkg/package.json
pnpm-lock.yaml

@swc/core 有时候发布的版本有 bug，为了避免影响正常编译，因此锁定 @swc/core 的版本

chore: lock @swc/core version

---

.changeset/strange-planes-push.md
packages/pkg/package.json
pnpm-lock.yaml

@ampproject/remapping 依赖在 @ice/pkg 安装的时候没有被安装，导致依赖缺失。
https://github.com/ice-lab/icepkg/blob/a2baa8cd70a6d9b7d35ddfdc62bebe27d7b0fcf0/packages/pkg/src/utils.ts#L17

fix: dependency is not installed

---

.changeset/README.md
.changeset/config.json
.changeset/pre.json
.changeset/pretty-lions-cry.md
.changeset/shaggy-wasps-occur.md
examples/application/package.json
examples/plugin/package.json
examples/react-component/package.json
examples/react-component/src/index.tsx
examples/react-multi-components/package.json
package.json
packages/pkg/CHANGELOG.md
packages/pkg/package.json
packages/pkg/src/rollupPlugins/swc.ts
packages/pkg/src/tasks/transform.ts
packages/pkg/src/utils.ts
packages/plugin-docusaurus/CHANGELOG.md
packages/plugin-docusaurus/package.json
packages/plugin-jsx-plus/CHANGELOG.md
packages/plugin-jsx-plus/package.json
packages/plugin-rax-component/package.json
pnpm-lock.yaml
website/docs/faq.md
website/docs/guide/abilities.md
website/docusaurus.config.js
website/package.json

为支持在组件的内联样式中编写 rpx 单位，需要把 react/jsx-runtime 改成 @ice/jsx-runtime：
```diff
- import { jsx as _jsx } from "react/jsx-runtime";
+ import { jsx as _jsx } from "@ice/jsx-runtime/jsx-runtime";
```
组件项目中需要依赖 @ice/jsx-runtime，对于老项目来说需要增加检测和提示新增 @ice/jsx-runtime 依赖。
模板修改：https://github.com/ice-lab/material-templates/pull/93

feat: specify @ice/jsx-runtime as jsx importSource

---

examples/application/package.json
examples/react-component/package.json
examples/react-multi-components/package.json
packages/plugin-docusaurus/package.json
packages/plugin-rax-component/package.json
pnpm-lock.yaml
website/package.json

@ice/jsx-runtime 依赖 react 18，项目内 react 依赖都统一升级到 18，避免多实例的问题出现

chore: upgrade react dep to 18

---

.changeset/mean-feet-melt.md
examples/application/index.js
examples/react-component/README.md
examples/react-component/docs/usage.md
packages/plugin-docusaurus/src/configureDocusaurus.mts
packages/plugin-docusaurus/src/template/docusaurus.hbs

使用 npm 安装依赖的时候，会出现无法 resolve @docusaurus/plugin-contents-page 的问题

fix: can not resolve @docusaurus/plugin-contents-page

---

.changeset/plenty-crews-rescue.md
packages/pkg/src/config/userConfig.ts

chore: add ICE_PKG_BUNDLE_OUTPUT_DIR to process.env

---

.changeset/wise-flowers-learn.md
packages/pkg/src/config/cliOptions.ts

没有任何地方有消费到 --dist，估计是为了watch bundle 产物的，和 build-plugin-component 一样https://www.npmjs.com/package/build-plugin-component

chore: remove dist cli option

---

packages/plugin-jsx-plus/src/index.ts

fix: jsx-plus plugin option

---

examples/rax-component/.eslintrc.js
packages/pkg/.eslintignore
packages/pkg/.eslintrc.mjs
packages/plugin-docusaurus/.eslintignore
packages/plugin-docusaurus/.eslintrc.cjs
packages/plugin-rax-component/.eslintignore
packages/plugin-rax-component/.eslintrc.mjs
website/docs/guide/abilities.md

- .eslintrc.mjs 是不生效的，故移除
- monorepo 里统一使用最外层的 .eslintrc.js 即可

chore: remove eslint config files

---

.changeset/shiny-wasps-reply.md
packages/pkg/src/rollupPlugins/babel.ts

如果使用 babel 编译 TSX 代码，会把顶层的 `import { createElement } from 'rax';` 给移除掉。
需要指定指定 `jsxPragma` 和 `jsxPragmaFrag` 告诉 @babel/plugin-transform-typescript 不要移除掉这两个模块导入
https://babeljs.io/docs/babel-plugin-transform-typescript#jsxpragma
https://babeljs.io/docs/babel-plugin-transform-typescript#jsxpragmafrag

fix: lose create element module in rax component

---

.changeset/few-lamps-remember.md
examples/react-component/pages/index.less
examples/react-component/pages/index.tsx
packages/plugin-docusaurus/package.json
packages/plugin-docusaurus/src/configureDocusaurus.mts
packages/plugin-docusaurus/src/plugin.js
packages/plugin-docusaurus/src/template/docusaurus.hbs
pnpm-lock.yaml
website/docs/faq.md

@ice/pkg-plugin-docusaurus 使用社区的 npm 包 `docusaurus-plugin-less` 和 `docusaurus-plugin-sass` 分别解析 less 和 sass。但我们使用子进程启动 docusaurus 本地预览服务，并且指定了 cwd 是 rootDir：
https://github.com/ice-lab/icepkg/blob/bca916d4093eda6f21995f8cea514fec100bbcc4/packages/plugin-docusaurus/src/doc.mts#L41
导致对于以下代码在 require `sass-loader` 的时候没法 resolve 到（因为是从项目根目录 node_modules 开始向上目录开始找）
https://github.com/rlamana/docusaurus-plugin-sass/blob/d97f88c3e24fd16477eac6d8f56a2703425ece9a/docusaurus-plugin-sass.js#L31
然后会报这样的错误：
虽然已经提了 PR，但一直没有发版本：
https://github.com/rlamana/docusaurus-plugin-sass/pull/25
因此考虑把 sass 和 less 的 webpack 解析规则内置到 docusaurus 插件

fix: sass-loader and less-loader can't be resolved

---

.changeset/moody-bugs-give.md
packages/plugin-docusaurus/src/plugin.js

在 less 和 scss 文件中编写的 rpx 单位没有转成 vw

fix: rpx2vw is invalid in less and scss

---

.changeset/lemon-keys-turn.md
examples/react-component/docs/usage.md
packages/plugin-docusaurus/src/Previewer/index.tsx
packages/plugin-docusaurus/src/genDemoPages/extractCodePlugin.mts
packages/plugin-docusaurus/src/remark/extractCode.js
packages/plugin-docusaurus/src/remark/getFileInfo.js
packages/plugin-docusaurus/src/remark/uniqueFilename.js

假设在 mdx 文件里有以下的内容，理论上能正常分别显示 XYZ 和 ABC：
但结果却是：

fix: can not render two components in one mdx file

---

.changeset/violet-lobsters-behave.md
packages/pkg/src/helpers/defaultSwcConfig.ts

fix: some es2017 syntaxs are not compatible with sarafi 10.1

---

.changeset/curly-cheetahs-hear.md
.changeset/gorgeous-frogs-repair.md
examples/plugin/src/index.ts
examples/plugin/tsconfig.json
examples/react-multi-components/build.config.mts
packages/pkg/src/helpers/defaultSwcConfig.ts
packages/pkg/src/helpers/getBuildTasks.ts
packages/pkg/src/types.ts
packages/plugin-rax-component/src/index.ts
website/docs/reference/plugins-development.md

支持使用 modifySwcCompileOptions 方法修改默认的 swc 配置：
```js
const plugin = (api) => {
const { onGetConfig } = api;
onGetConfig(config => {
config.modifySwcCompileOptions = (originOptions) => {
const newOptions = { ...originOptions, env: { } };
return newOptions;
}
});
};
```

feat: support modify swc compile options

---

.changeset/unlucky-radios-tease.md
packages/pkg/src/config/userConfig.ts
packages/pkg/src/helpers/defaultSwcConfig.ts
packages/pkg/src/types.ts
website/docs/reference/config.md

在组件层面，组件的产物不应该引入任何 polyfill 的内容，而是由上层应用决定的。现在有一些 bundle 产物体积很大，原因是把 polyfill 也打包进去了，影响了性能。
为了解决上面的问题，同时要兼容以前的表现，新增 `bundle.polyfill` 配置。支持配置在 bundle 模式下 polyfill 注入的规则。当前默认值兼容现在的表现，推荐使用 false，并在下一个版本修改为 false

feat: support `bundle.polyfill` config

---

.changeset/four-beans-hang.md
packages/create-pkg/src/index.mts
packages/create-pkg/src/inquireTemplateNpmName.ts

指定了 `-w` 参数（以指定创建子项目），不应该显示 monorepo 模板的选项

fix: show monorepo template when create a sub package

---

.changeset/green-hairs-join.md
packages/create-pkg/src/index.mts

创建子项目的时候，不应该增加 docusaurus 插件
Ref: https://github.com/ice-lab/material-templates/pull/99/files

feat: add workspace template option

---

examples/rax-component/package.json
examples/react-component/package.json
examples/react-multi-components/package.json
packages/pkg/package.json
packages/pkg/src/helpers/defaultSwcConfig.ts
packages/pkg/src/helpers/getRollupOptions.ts
packages/pkg/src/rollupPlugins/swc.ts
packages/pkg/src/tasks/transform.ts
pnpm-lock.yaml

升级新版本的 @swc/core 后，原来配置的字段 filename 用法不正确，导致出现下面的问题：
而源码的写法是：
核心是之前 baseUrl 设置有问题，在 swc pr https://github.com/swc-project/swc/issues/1324 被修正过来
另外：
1. 原来的 filename 是为了纠正 sourcemap 里面的 sources 字段，最正确的做法是使用 sourceFilename 字段
2. sources 字段中不应使用绝对路径，大部分的场景都是使用相对路径

fix: swc auto transform .mjs to .mts suffix in output file content

---

.changeset/late-goats-fly.md
examples/rax-component/package.json
examples/react-component/package.json
examples/react-multi-components/package.json
packages/pkg/package.json
packages/pkg/src/helpers/defaultSwcConfig.ts
packages/pkg/src/helpers/getRollupOptions.ts
packages/pkg/src/rollupPlugins/swc.ts
packages/pkg/src/tasks/transform.ts
packages/plugin-docusaurus/src/constants.mts
packages/plugin-docusaurus/src/genDemoPages/index.mts
packages/plugin-docusaurus/src/index.mts
pnpm-lock.yaml
website/docs/guide/preview.md

在 monorepo 项目中，执行 pnpm build 进行文档构建时，没有生成 demo 文件，导致移动端页面预览失效：
主要问题是下面的代码片段中，没考虑 monorepo 文档部署的场景：
https://github.com/ice-lab/icepkg/blob/c4979e8d4a726fee779e7138854712e3cbd6e87c/packages/plugin-docusaurus/src/index.mts#L50

fix: not generate demo pages

---

packages/pkg/package.json
packages/plugin-docusaurus/package.json
packages/plugin-jsx-plus/package.json
packages/plugin-rax-component/package.json
packages/remark-react-docgen-docusaurus/package.json

在发包的时候，可能会多个包同时执行 prepublishOnly 的脚本，当包与包之间有相互依赖关系时，就会导致构建失败
https://github.com/ice-lab/icepkg/actions/runs/4945744983/jobs/8842882823

fix: release version error

---

.changeset/fair-lobsters-grow.md
packages/plugin-docusaurus/src/plugin.js

问题：使用 tnpm/cnpm 安装依赖时，当保存代码时，可能会出现内存溢出的问题。
原因是因为 webpack5 的持久缓存无法生成，与 ice.js 3 解决方法一致。

fix: tnpm oom

---

.changeset/breezy-glasses-guess.md
packages/pkg/src/utils.ts

bundle 产物并没有把 node_modules 中包给编译处理，理论上应该要跟对应的语法 target 保持一致

fix: not transform node_modules packages

---

.changeset/thick-wombats-look.md
packages/pkg/src/config/userConfig.ts
packages/pkg/src/helpers/getRollupOptions.ts
packages/pkg/src/rollupPlugins/babel.ts
packages/pkg/src/rollupPlugins/swc.ts
packages/pkg/src/types.ts
packages/pkg/src/utils.ts
website/docs/reference/config.md

之前的 [PR](https://github.com/ice-lab/icepkg/pull/552)，默认就会把所有的 node_modules 下的依赖都编译了一遍，导致跟之前版本有 Break Change。比如：
classnames 的源文件就只有一个 IIFE，没有任何导出，导致在打包编译过程中会找不到任何导出，就会出现上面的报错。
因此需要增加一个配置项来决定是否要编译 node_modules

feat: support configure compile deps

---

.changeset/heavy-kids-play.md
packages/plugin-docusaurus/src/configureDocusaurus.mts

Docusaurus 启动的时候，目前是读取根目录的 package.json，如果 package.json 中指定了 type: module，则 `.docusaurus` 临时目录的文件（是 docusaurus 生成的）将会报错

fix: specify type module in package.json will occur build error

---

.changeset/beige-numbers-wink.md
packages/pkg/package.json
packages/plugin-docusaurus/src/configureDocusaurus.mts
pnpm-lock.yaml

关联 #560 
在 md 文件中显示声明引入当前 npm 包时，无法正确 require 到。这是因为向上逐层查找 node_modules 是否有此 npm 包，发现并没有。解决方案是通过软链接的方式链到根目录 node_modules

fix: not resolve package in docs

---

packages/plugin-docusaurus/CHANGELOG.md
packages/plugin-docusaurus/package.json
packages/plugin-docusaurus/src/configureDocusaurus.mts

如果父路径不存在，则在进行创建软链接过程中会出现路径不存在的报错。使用 [fs.ensureSymlinkSync](https://github.com/jprichardson/node-fs-extra/blob/master/docs/ensureSymlink-sync.md) 可以保证父路径存在

fix: symlink error when dir doesn't exists

---

website/docs/guide/monorepo.md
website/docs/quick-start.md

在 npm v7 使用以下方式创建子包，会导致 -w 参数无法传递过去。一般需要加 `--`
```diff
- $ npm init @ice/pkg -w packages/your-lib
+ $ npm init @ice/pkg -- -w packages/your-lib
```
Monorepo 章节统一使用 pnpm 操作。
另外，顺带修改『快速开始』章节的创建项目部分，增加 @latest 确保每次都使用最新的 cli 版本进行创建

docs: fix create pkg with workspace cli flag

---

examples/react-component/src/components/Test/index.css
examples/react-component/src/components/Test/index.jsx
packages/pkg/package.json
packages/pkg/src/helpers/getRollupOptions.ts
pnpm-lock.yaml

在 bundle 模式下，大部分场景下是作为外部资源（比如 umd）加载的，浏览器不能识别 rpx，因此需要在构建时支持把 rpx 转换成 vw 。

feat: support transform rpx to vw in bundle mode

---

.changeset/few-crabs-sneeze.md
examples/react-component/src/components/Button/index.tsx
examples/react-component/src/typings.d.ts
packages/pkg/src/helpers/dts.ts

如果某些类型直接被定义在 `.d.ts` 文件中，在实际的 `.ts` 文件中通过全局类型的方式使用，而不是通过模块导入的形式使用。比如：
```ts
// types.d.ts
interface Application {
onClick: () => void;
}
```
```ts
// src/index.ts
export app: Application = {
onClick: () => {}
}
```
生成 d.ts 文件时候会报错：`TS4025: Exported variable '<name>' has or is using private name '<name>'.`
解决的办法是，在 `ts.createProgram(programOptions)` 中，`programOptions.rootNames` 要把对应的 `d.ts` 声明文件包含，才能编译成功。

fix: generate type with private type error

---

.changeset/slow-students-shop.md
.npmrc
packages/pkg/src/helpers/dts.ts

修复dts生成失败时 `dtsFiles` 和 `_file` 不匹配的问题，tsc-alias的source为必填项 否则会报错
避免dts的生成阻塞构建
[reproduce repo](https://github.com/HomyeeKing/icepkg-repro)

fix: dts maybe failed

---

.changeset/eighty-sheep-wait.md
packages/plugin-docusaurus/src/configureDocusaurus.mts
packages/plugin-docusaurus/src/formatWinPath.cjs
packages/plugin-docusaurus/src/formatWinPath.cts
packages/plugin-docusaurus/src/remark/extractCode.js
packages/plugin-docusaurus/src/remark/getFileInfo.js
packages/plugin-docusaurus/src/remark/resolveImports.js

`Function.prototype.toString()` 会把中文转成 unicode 编码，然后经过 `String.protype.replace()` 会在 unicode 编码前面多增加 `\`。比如：
```diff
- \u4e2d
+ \\u4e2d
```
https://github.com/ice-lab/icepkg/blob/0d3f4ae4046e7082e8c3ae557a4c1dcb829dc086/packages/plugin-docusaurus/src/configureDocusaurus.mts#L30-L32
补充：
还修复了在 windows 下无法启动的问题

fix：unicode will be transformed

---

.changeset/hip-oranges-reflect.md
packages/pkg/CHANGELOG.md
packages/pkg/package.json
packages/pkg/src/helpers/getRollupOptions.ts
packages/pkg/src/types.ts

bundle 模式下，如果不同的 task(比如一个 weex，一个 web )均产生 vendor，因为 vendor 文件同名的原因，那么后面产出的 vendor 会覆盖掉前面的 vendor。
因此需要支持每个 task 定制自己的 vendor name

feat: support modify vendor name

---

.changeset/giant-wolves-press.md
packages/pkg/src/rollupPlugins/babel.ts
packages/pkg/src/rollupPlugins/swc.ts
packages/pkg/src/types.ts
packages/pkg/src/utils.ts
packages/pkg/tests/babelPlugin.test.ts
packages/pkg/tests/formatCnpmDepFilepath.test.ts
website/docs/reference/config.md

问题 ：当指定编译某个依赖后，会把所有的 node_modules 依赖都编译了
修复上述问题后，并支持传入 compileDependencies 为 `string[]` 类型

fix: compile all deps when specify deps in compileDependencies

---

.changeset/two-bobcats-sparkle.md
packages/pkg/src/rollupPlugins/swc.ts

对于在编译 node_modules 依赖的场景下，swc 会使用 esm 的方式 import @swc/helpers 的模块。如果文件原来是 cjs 模块，导致变成了 esm 模块，导致后面的解析有问题。
经过 swc 编译的代码，如果判断是 cjs 模块，再 transform import('@swc/helpers/xx') -> require('@swc/helpers/xx')

fix: add esm @swc/helpers module to cjs module by swc

---

.changeset/sharp-lobsters-pay.md
.github/workflows/release-snapshot.yml
packages/pkg/src/utils.ts

对于要编译除 node_modules 下某几个包以外的所有 npm 包，用户写下面的代码：
```js
compileDependencies: [/((?!(classnames\/|lodash\/)).)+/]
```
目前的正则匹配实现，如果是有包与包之间的依赖关系，也会把 lodash/classnames 也编译进去：
比如：
- lodash-es
- lodash 
https://regex101.com/r/antWRA/2

fix: not exclude deps

---

.changeset/lazy-insects-own.md
packages/pkg/src/utils.ts
packages/pkg/tests/createScriptsFilter.test.ts

兼容之前的逻辑，默认编译非 node_modules 下的 js/ts 文件。
> 下个大版本可以只考虑编译 src 下的 js/ts 文件
https://github.com/ice-lab/icepkg/blob/1596db0e3bdd77cb2e527694fdf792d7cae4cec4/packages/pkg/src/utils.ts#L297C2-L297C2

fix: not compile non src entry

---

.changeset/seven-ravens-know.md
packages/pkg/src/rollupPlugins/dts.ts

修复dts文件写入逻辑
写入路径不需要依赖entires，否则会导致相对路径错误
生成dts时需保证dtsPath为绝对路径，后续直接读取即可
https://github.com/ice-lab/icepkg/blob/c122c90d1eb3df253e8a0a301d75f8e2e8c0adab/packages/pkg/src/tasks/transform.ts#L141 这里保证了入口文件地址为绝对路径
case: 
现在设置了多entry  保留了原始目录 比如
src下有foo bar两个文件夹
最终构建出会保留foo bar两个文件夹 
但是之前的dts文件地址 是遍历了所有entry，然后取的相对路径，  
这时候 foo/a.d.ts 遍历到entry为foo时，为./a.d.ts  当遍历到entry为bar时 相对路径成了../a.d.ts  然后写入的时候 路径就不对了

fix: dts file write

---

packages/pkg/CHANGELOG.md
packages/pkg/package.json
packages/pkg/src/rollupPlugins/alias.ts

#633 在windows上path返回的路径分隔为\，编译后的路径错误
修改后可以正常通过单测

fix: alias incorrect on windows

---

.changeset/new-pears-arrive.md
.changeset/plenty-avocados-know.md
.changeset/sweet-plums-rush.md
.gitignore
packages/pkg/src/helpers/dts.ts
packages/pkg/src/helpers/getBuildTasks.ts
packages/pkg/src/tasks/transform.ts
packages/pkg/tests/fixtures/alias/build.config.default.mts
packages/pkg/tests/fixtures/alias/package.json
packages/pkg/tests/fixtures/alias/src/alias.ts
packages/pkg/tests/fixtures/alias/src/index.ts
packages/pkg/tests/fixtures/alias/tsconfig.json
packages/pkg/tests/fixtures/default/package.json
packages/pkg/tests/fixtures/default/src/index.ts
packages/pkg/tests/fixtures/tsconfig.common.json
packages/pkg/tests/projects/__snapshots__/alias.test.ts.snap
packages/pkg/tests/projects/__snapshots__/default.test.ts.snap
packages/pkg/tests/projects/alias.test.ts
packages/pkg/tests/projects/default.test.ts
packages/pkg/tests/projects/helper.ts
pnpm-lock.yaml
pnpm-workspace.yaml

Three bugs are fixed.
- fix: bundle mode with start command should be `development` environment instead of `production`
- fix: alias is should be working for .d.ts file
- fix: sourcemap option should be working and default should be false for transform

fix: alias/sourcemap/bundle_mode bug

---

.changeset/khaki-bananas-march.md
.gitignore
packages/pkg/src/helpers/getBabelOptions.ts
packages/pkg/src/helpers/getRollupOptions.ts
packages/pkg/src/types.ts
packages/pkg/tests/babelPlugin.test.ts
packages/pkg/tests/fixtures/bundle-browser/package.json
packages/pkg/tests/fixtures/bundle-browser/src/index.ts
packages/pkg/tests/fixtures/mock-entry-package/browser.js
packages/pkg/tests/fixtures/mock-entry-package/index.d.ts
packages/pkg/tests/fixtures/mock-entry-package/main.js
packages/pkg/tests/fixtures/mock-entry-package/module.js
packages/pkg/tests/fixtures/mock-entry-package/package.json
packages/pkg/tests/projects/__snapshots__/bundle-browser.test.ts.snap
packages/pkg/tests/projects/bundle-browser.test.ts
pnpm-lock.yaml
website/docs/reference/config.md

feat: support browser option for bundle

---

.changeset/sharp-starfishes-eat.md
packages/pkg/src/commands/start.ts
packages/pkg/src/helpers/watcher.ts
packages/pkg/src/tasks/bundle.ts
packages/pkg/src/tasks/transform.ts
packages/pkg/src/types.ts

主要修了两个问题
- watcher 监听文件的事件没有 batch，导致同时修改多个文件的话会同时重新编译多次，这里手动加了 250ms debounce，暂时不支持配置，后续打算重构这块
- watcher 需要等待第一次启动成功启动后，才能触发相应的事件，否则会报常量未初始化的错误，这里加了一个 beginBlock/endBlock 的方法拦截一下，这期间的所有文件事件都会被缓存，直到第一次启动成功后调用 endBlock 再统一消费

feat: add batch for watcher change event

---

.changeset/light-crews-return.md
packages/pkg/src/helpers/getRollupOptions.ts
packages/pkg/tests/projects/__snapshots__/alias.test.ts.snap

This reverts commit 3e6f78aed477809551dd989cc05979960512ca9e.
测试发现当 jsx 混用的情况下，先处理 alias 会导致解析出现问题，所以先 revert 掉，等后续多补充些测试 case。

Revert "fix: cjs format should support alias for .d.ts file (#670)"
